# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 068cd7f6d75ee50d46c2c84b70ee29fb57f3904c2a484cce3af533af9046873ff1fa30b7da308d8c36237530a0607e8a1f3c8d5ef65b3fad1f69d794612ff695

test:
  secret_key_base: 16e6f4ebaafab0bc6f34bb8c80616bf66ec58b411ebe27b88c2065b956eb0bf394a1fae17a1fb141e80e48379d5262037cc0c8a83c0dd7810a7a193ec0da8a68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
